version: '3.7'

services:
  euprostir:
    image: danlynn/ember-cli:3.1.4-node_10.1
    hostname: euprostir
    container_name: euprostir
    volumes:
      - .:/myapp
      - .bash_history:/root/.bash_history
      - node_modules:/myapp/node_modules
    tmpfs:
      - /myapp/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
    command: "ember server --environment=master"

volumes:
  node_modules:
