version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 4200:4200
    volumes:
    - .:/app
    - node_modules:/app/node_modules
volumes:
  node_modules:
